### ISSUE TITLE
Collabora - Activate Admin console

### ISSUE THREAD

**Issue by dzatoah** [sunweaver/nextcloud-high-performance-backend-setup#1]
* Generate Admin username + Password

~~* Put that stuff into /etc/coolwsd/coolwsd.xml~~
* `echo -e "admin\n12345678\n12345678" | coolconfig set-admin-password`

The Admin panel is available under `https://<domain>/collabora/browser/dist/admin/adminSettings.html`

**Comment by PhilDevProg** [comment]
More information: https://sdk.collaboraonline.com/docs/installation/Configuration.html#admin-console

**Comment by mircokam** [comment]
Kann bei Bedarf jeder von Hand starten. Daz ubenötig es keine Config
