### ISSUE TITLE
Add Recording Server for Talk

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#102]
Hier ist eine Anleitung wie man den Aufsetzt:
https://help.nextcloud.com/t/how-to-setup-nextcloud-talk-recording-backend/159145/38

**Comment by caloracloud** [comment]
Hi Mirco.
First of all...Thanks for your hardwork !!

Do you have any idea when will you going to implement the recording feature to your script?

Best Regards !!!

**Comment by mircokam** [comment]
Hello,
sorry not in the moment. If i understand it correct is this more a part on  the Nextcloud Server.
Best Regards !!!
