### ISSUE TITLE
nats-io is not built from source, only works on x86

### ISSUE THREAD

**Issue by madscientist159** [sunweaver/nextcloud-high-performance-backend-setup#104]
The install script blindly downloads the prebuilt x86 executable for nats-io instead of building from source.  This results in a failure on all non-x86 systems, including OpenPOWER.

The script should instead pull nats-io source from GIT, then run 'go build' and copy the resulting `nats-server` executable to `/usr/local/bin`.  This is confirmed working on an OpenPOWER server.

**Comment by PhilDevProg** [comment]
For ARM the script could just download the arm executable if the system has an ARM chip.

**Comment by dzatoah** [comment]
Can this issue be closed?

**Comment by mircokam** [comment]
We can’t test this. I close this.
