### ISSUE TITLE
Update for compatability with NC 26.0.1

### ISSUE THREAD

**Issue by andreasdueren** [sunweaver/nextcloud-high-performance-backend-setup#105]
Currently it throws the error `Error: Running version: unknown; Server needs to be updated to be compatible with this version of Talk`

**Comment by mircokam** [comment]
Hallo Andreas,
wo wift er den den Fehler?
Ich habe eine Nextcloud 26.0.1 mit Talk 16.03 und das funktioniert soweit. Den Server hab ich vor zwei Wochen installiert.

**Comment by andreasdueren** [comment]
Im Administrator-UI im Talk bereich wenn man die Daten dort eingibt. Kam nach meinem Update zu NC 26 auf, hatte vorher immer alles geklappt gehabt.

**Comment by andreasdueren** [comment]
Einfach das Script `setup-nextcloud-hpb.sh` neu laufen lassen?

**Comment by mircokam** [comment]
Sollte so funktionieren. Sonst halt neu aufsetzen.

**Comment by andreasdueren** [comment]
Scheint zu funktionieren, danke!

**Comment by andreasdueren** [comment]
Tatsächlich funktionierts doch noch nicht, beim Testen können die Clients keine Verbindung miteinander aufbauen. Ich setze mal ein frisches System auf.

**Comment by andreasdueren** [comment]
Nein, auch mit einem frischen Server funktioniert das leider nicht. Ich habe leider im Augenblick keine Zeit, das weiter zu untersuchen, mache mich demnächst nochmal dran ob ich mehr herausfinden kann.

**Comment by mircokam** [comment]
Wie gesagt,
bei mir mit Nextcloud 26.0.1 und Talk 16.03 funktioniert das ohne Probleme.

**Comment by andreasdueren** [comment]
Ja das ist sehr merkwürdig. Ich habe die gleichen Versionen von NC und TALK am laufen und das Script auf einem frischen Server laufen lassen. Zwar wird im Admin-UI alles schön grünn angezeigt, aber die Geräte können keine Verbindung miteinander aufbauen.

**Comment by PhilDevProg** [comment]
Bist du dir sicher, dass alles richtig kopiert ist und nicht irgendwo vielleicht ein Leerzeichen zu viel ist?

**Comment by andreasdueren** [comment]
> Bist du dir sicher, dass alles richtig kopiert ist und nicht irgendwo vielleicht ein Leerzeichen zu viel ist?

Ja, ich habe die einstellungen mehrfach neu eingegeben.

**Comment by qroac** [comment]
Ich habe das HPB gerade eben auf einer frischen Hetzner VM (Debian 12) mit dem letzten Release des Skripts aufgesetzt.
Die Admin-Page zu Talk meldet mir nach der Installation:
> Fehler: Aktuelle Version: unreleased; Server muss aktualisiert werden, um mit dieser Version von Talk kompatibel zu sein
