### ISSUE TITLE
Reverse Proxy

### ISSUE THREAD

**Issue by uruzFR** [sunweaver/nextcloud-high-performance-backend-setup#107]
I have successfully installed and configured my VM, redirecting ports 80, 443 and 5349 to it. However, I'm having trouble setting up Nginx as a reverse proxy to handle multiple services. I need assistance with the configuration.

I have successfully redirected port 443 using Nginx Proxy Manager. However, I need assistance with further configuration to properly handle multiple services through the reverse proxy.I don’t know how to redirect port 5349 with proxy manager

**Comment by mircokam** [comment]
Hello,
project is not for use behind a proxy. 
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/01-Voraussetzung
Ein Server mit einer öffentlich zugänglichen IP! (nicht für Systeme hinter einer Firewall oder NAT mit privater Adresse) 

Sorry
