### ISSUE TITLE
Signalling server doesn't work after installation

### ISSUE THREAD

**Issue by edodark** [sunweaver/nextcloud-high-performance-backend-setup#108]
After running the script everything is installed, no error, it's perfectly installed and it give me every info to connect talk to turn signalling ecc.
The turn server works perfectly but the signalling server is the problem.
It's giving me an error saying that he can't connect. Any way to fix this?

**Comment by LaserGrunt** [comment]
How did you get past the Go crypto/ecdh pull issue ?

**Comment by edodark** [comment]
> How did you get past the Go crypto/ecdh pull issue ?

i haven't got any type of error, it's just the signalling that doesn't work, do you know how to fix this?

**Comment by dzatoah** [comment]
I'd suggest you post a copy of the `nextcloud-spreed-signaling` , `nats-server`, `janus`  and `coturn` log files. Don't forget to censor critical information (like IP's or domain names).

**Comment by edodark** [comment]
Where are the log stored ?On 24 Jul 2023, at 13:52, Daniel ***@***.***> wrote:﻿
I'd suggest you post a copy of the nextcloud-spreed-signaling , nats-server, janus  and coturn log files. Don't forget to censor critical information (like IP's or domain names).

**Comment by edodark** [comment]
Also i add that when i write every info in the signalling server setting it gives me the green check but there is the voice version: and it doesn't show any version number

**Comment by mircokam** [comment]
Yes i know that there is no Version Number. I think is it a good idea to check this.

**Comment by mircokam** [comment]
Unter Debian 12 lässt sich das zuverlässig installieren. Ich habe für die Verisonsnummer des Signalings einen neuen Fehler angelegt:
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/122

**Comment by dankrue80** [comment]
Hey guys, I encountered the same issue. Just installed v1.2.4 on a Debian 12 vps. Installation went through without any errors. STUN and TURN servers seem to work fine with Nextcloud. I get the green checkmark on TURN Server there. But the signalling server under High-performance backend settings is giving back `Error: Server responded with: 502`.

![Bildschirmfoto 2023-11-21 um 14 26 07](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/assets/39704296/d2a52d97-0a48-4049-b52e-4319ae5329c5)

Any help would be highly appreciated.

**Comment by mh-74** [comment]
Hallo,
gibt es eine Lösung für den Fehler 502? Das Script läuft sauber durch. (v1.2.4 on a Debian 12 vps)

**Comment by dankrue80** [comment]
Ich habe leider bisher keine Lösung. Bin der Sache in diesem Issue hier noch etwas auf den Grund gegangen, habe aber leider keine hilfreiche Antwort erhalten.
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/129

**Comment by mh-74** [comment]
Kann es sein, dass es etwas mit der Go Version zu tun hat? Ich habe es letztes Jahr mit Debian 11 auf einem VPS bei Strato getestet, da lief es noch. Jetzt weder mit 11 noch mit 12. Das Script läuft durch, aber der Signaling Server wird, denke ich garnicht installiert.

**Comment by dankrue80** [comment]
Ja, denke auch dass das was mit der Go Version zu tun haben könnte. Der Signaling Server wird jedenfalls nach erfolgreichem Durchlaufen des Scripts nicht korrekt ausgeführt. Schau mal in das zuvor verlinkte Issue.
