### ISSUE TITLE
Android Talk App liefert kein Videobild mit Janus 1.x

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#109]
Anfrage Kunde:

ich hab ein kleines Problem...
In ihrem Skript scheint eine alte Version von Janus verwendet zu werden.
Wird dies in naher Zukunft geupdatet?
Denn ich habe das Problem das ich auf den Mobilgeräten keine eingehenden Videos sehen kann.
Oder haben sie ne gute Idee wie ich Janus am besten updaten kann? 

Paket:
https://tracker.debian.org/pkg/janus

Heir sollte eine Anfrage an den Maintainer erfolgen ob die das Paket in Backports aktualiesieren können.

**Comment by fn00rd** [comment]
Es scheint mir eher so zu sein, als wäre der komplette 1.x Branch von Janus nicht kompatibel mit Talk für Android. Das ist laut diesem [Beitrag ](https://github.com/nextcloud/talk-android/issues/2704#issuecomment-1645121920) hier bei den Entwicklern bekannt, jedoch scheint mir die Bereitschaft zu einem Fix von Talk für Android eher gering, denn "der 0.x Branch wird ja noch maintained". 

Vielleicht könnte man daher eher bei der Installation des HPB abfragen, welcher Branch verwendet werden soll? Wenn ich keine Android-Geräte in meiner Umgebung habe, möchte ich ja bestimmt die neuere Janus-Version mit mehr Features nutzen. Denn bis auf den Android-Client funktioniert der 1.x Branch (soweit ich das getestet habe) wunderbar.

**Comment by mircokam** [comment]
Hallo,
das Ziel sollte sein das die Pakete alle Lauffähig in Debian oder Debian Backports mit den jeweils aktuellen Versionen landen. Wir werdne mal testen ob der Fix funktioniert.

https://github.com/nextcloud/talk-android/issues/2704#issuecomment-1638210245

**Comment by lugau45** [comment]
Gibt es schon Neuigkeiten wie das Problem gelöst werden kann? Im Browser geht es super aber auf Android nicht.

**Comment by mircokam** [comment]
https://github.com/nextcloud/spreed/issues/10003
https://github.com/strukturag/nextcloud-spreed-signaling/issues/280
https://github.com/meetecho/janus-gateway/issues/2566

**Comment by fn00rd** [comment]
oh happy days: mit dieser apk funktioniert eingehendes Video jetzt bei mir mit HPB

https://github.com/nextcloud/talk-android/pull/3670#issuecomment-1967574936

**Comment by lugau45** [comment]
Ja, endlich klappt es mit dem HPB :)

**Comment by PhilDevProg** [comment]
Da dieses Problem endlich gelöst ist, schließe ich diese Issue. 🎉

**Comment by mircokam** [comment]
Es klappt direkt mit der APP aus dem Android Store :-)

**Comment by mircokam** [comment]
Hello,
we testet the Android App Talk Version 18.1.0 on Pixel 7 with Janus 1.x Multistream  an Nextcloud 28.0.3 and Talk 18.0.5 and nextcloud-spreed-signaling 1.2.3 an it works now with video. :-) 

https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/109
