### ISSUE TITLE
data/*: Update config files

### ISSUE THREAD

**Issue by dzatoah** [sunweaver/nextcloud-high-performance-backend-setup#113]
Update config files without breaking Debian 11 support

**Comment by mircokam** [comment]
DEbian 11 Support ist hier nicht wichtig da wir ja mit 12 Stabil sind!

**Comment by sunweaver** [comment]
We will drop Debian 11 support, so please deploy config templates taken from packages in Debian 12.

**Comment by mircokam** [comment]
I close this. We support only Debian Bookworm
