### ISSUE TITLE
Complete Wiki

### ISSUE THREAD

**Issue by PhilDevProg** [sunweaver/nextcloud-high-performance-backend-setup#12]
- [x] Write [Requirements page](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/01-Voraussetzung)
- [x] Complete [Example usecases page](https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/05-Bsp-Anwendungen)

**Comment by mircokam** [comment]
Folgende Seiten sind jetz in dem Wiki überarbeitet:
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/01-Voraussetzung
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/02-Setup-Script
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/03-Nextcloud-Einstellung
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/04-Android-und-IOS

als nächstes folgt noch:
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/wiki/05-Bsp-Anwendungen

**Comment by Daijan80** [comment]
Hallo, fehlen würde noch in der Dokumentation, welche Ports alle geöffnet werden müssten
Ansonsten echt tolles Projekt.
LG

**Comment by mircokam** [comment]
Eigentlich macht das Script alle Ports passend auf. Da die Verbindung von der Nextcloud aus aufgebaut wird sollte da auch kein Problem entstehen.
Danke

**Comment by Daijan80** [comment]
Ja, aber ich muss die Ports ja auch in FRITZ!Box/Reversproxy öffnen, wenn ich beides via Internet erreichbar haben möchte, oder?

**Comment by mircokam** [comment]
Eigentlich soll beides im Internet stehen. Dann muss man auch in der Fritzbox nichts ändern. So wie es sich anhört willst Du einen Teil in Deinem internen Netz betreiben.  Das weiß ich aber nicht. Vieleicht hilft Dir der Status der Ufw Firewall des Scripts:

root@debian:/home# sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
OpenSSH                    ALLOW       Anywhere                  
WWW Full                   ALLOW       Anywhere                   # Nextcloud HPB Nginx
5349                       ALLOW       Anywhere                   # Nextcloud HPB Coturn
OpenSSH (v6)               ALLOW       Anywhere (v6)             
WWW Full (v6)              ALLOW       Anywhere (v6)              # Nextcloud HPB Nginx
5349 (v6)                  ALLOW       Anywhere (v6)              # Nextcloud HPB Coturn

**Comment by Daijan80** [comment]
Doch, wenn der Server bei einem zu Hause steht und hinter der FRITZ!Box und Reversproxy.
Danke, das hilft erstmal.
