### ISSUE TITLE
ERROR: Could not find a profile matching 'WWW Full'

### ISSUE THREAD

**Issue by lugau45** [sunweaver/nextcloud-high-performance-backend-setup#124]
Step 2: Configure firewall
Default incoming policy changed to 'deny'
(be sure to update your rules accordingly)
Default outgoing policy changed to 'allow'
(be sure to update your rules accordingly)
Skipping adding existing rule
Skipping adding existing rule (v6)
ERROR: Could not find a profile matching 'WWW Full'

Was kann ich tun?
Server ist ein oracle arm 

MfG
Marco

**Comment by dzatoah** [comment]
Please take a look at https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/18

Greetings, Daniel

**Comment by lugau45** [comment]
Danke

**Comment by lugau45** [comment]
Nun kommt
`Created symlink /etc/systemd/user/sockets.target.wants/pk-debconf-helper.socket → /usr/lib/systemd/user/pk-debconf-helper.socket.
Setting up packagekit-tools (1.2.5-2ubuntu2) ...
Setting up software-properties-common (0.99.22.7) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
Unable to handle repository shortcut 'contrib'
`

**Comment by PhilDevProg** [comment]
Vielleicht sollte das Skript einfach gucken, ob die Datei existiert und wenn nicht, sie mit dem Inhalt aus #18 anlegen.

**Comment by PhilDevProg** [comment]
> Nun kommt
> `Created symlink /etc/systemd/user/sockets.target.wants/pk-debconf-helper.socket → /usr/lib/systemd/user/pk-debconf-helper.socket.
> Setting up packagekit-tools (1.2.5-2ubuntu2) ...
> Setting up software-properties-common (0.99.22.7) ...
> Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
> Processing triggers for dbus (1.12.20-2ubuntu4.1) ...
> Unable to handle repository shortcut 'contrib'
> `

It looks like you are using Ubuntu. The script only supports Debian 12, please us this instead of Ubuntu.

**Comment by lugau45** [comment]
Es scheint wohl nicht mit Ubuntu zu gehen, naja kann man nichts machen.

**Comment by PhilDevProg** [comment]
Kannst du gucken, ob das Original-Problem auch unter Debian 12 auftaucht? Ubuntu liefert die benötigte Datei standartmäßig nicht mit, aber es wird vom Skript ja auch nicht unterstützt.

**Comment by lugau45** [comment]
Auf dem Server wo ich es testen wollte leider nicht, da geht nur Ubuntu. Ich kann es aber auf einer anderen vm dann mal testen.
