### ISSUE TITLE
Add support for ppc64le hosts

### ISSUE THREAD

**Issue by madscientist159** [sunweaver/nextcloud-high-performance-backend-setup#126]
OpenPOWER (ppc64le) hosts represent the only open ISA with performance comparable to amd64 machines.  As support is a relatively simple matter of detecting the architecture and using the appropriate configuration file, I would like to see support added in vs. needing to maintain a fork.

Thank you!

**Comment by PhilDevProg** [comment]
I added the improvements of #125 back but we don't have the hardware to test the script on ppc64le so we can't assure you that everything works or that everything will work in the future.

**Comment by mircokam** [comment]
Hello, 
i close this now.
