### ISSUE TITLE
Nachträglich ein Server hinzufügen 

### ISSUE THREAD

**Issue by lugau45** [sunweaver/nextcloud-high-performance-backend-setup#131]
Hallo, ich muss mal fragen wie man nachträglich ein Server hinzufügt das dieser alles nutzen kann. Einfach das Setup erneut starten oder manuell alles überall (wenn ja wo) eintragen?

**Comment by dzatoah** [comment]
Du kannst das Skript einfach nochmal ausführen :)

**Comment by lugau45** [comment]
Ok und danke für die Antwort. Ich habe mich jetzt aber mal durch die configs gewühlt und alles mit der Hand eingetragen, das ist ja dann doch nicht so wild. Läuft jetzt alles so wie es soll. Noch eine Frage, ein Aufzeichnungs-Backend  ist nicht dabei oder? Ich weiß zwar nicht genau wozu das da ist, aber wenn es vorhanden ist, könnte man es ja nutzen.

**Comment by dzatoah** [comment]
@mircokam Aufzeichnungsbackend?

**Comment by mircokam** [comment]
Nein das Recording Backend ist nicht dabei. du must das Script neu starten. Es werden dann aber auch für alle Adressen neue Keys erzeugt.
