### ISSUE TITLE
Add support for eturnal as an alternative STUN/TURN server

### ISSUE THREAD

**Issue by christopher7711** [sunweaver/nextcloud-high-performance-backend-setup#132]
Hey, I had issues maybe non reproducible with setting up this script with coturn it was not starting because it could not bind to the ports sorry i don't have the logs of the error message anymore. Several reinstalls later i replaced coturn with eturnal after running the script and everything is running smooth now.

eturnal is also an option in the official Nextcloud Documentation.

**Comment by christopher7711** [comment]
Ok found the issue I also had https://github.com/coturn/coturn/issues/1206 maybe there was an solution but also tried all of those suggested things.

**Comment by christopher7711** [comment]
fresh debian 12 install from the hoster contabo and just running the commands from the tutorial:

root@aasdoif:~# systemctl status coturn
● coturn.service - coTURN 4STUN/TURN Server
     Loaded: loaded (/lib/systemd/system/coturn.service; enabled; preset: enabled)
     Active: activating (start) since Fri 2023-12-01 03:17:04 CET; 3s ago
       Docs: man:coturn(1)
             man:turnadmin(1)
             man:turnserver(1)
   Main PID: 12613 (turnserver)
      Tasks: 7 (limit: 19137)
     Memory: 9.7M
        CPU: 80ms
     CGroup: /system.slice/coturn.service
             └─12613 /usr/bin/turnserver -c /etc/turnserver.conf --pidfile=

Dec 01 03:17:38 host turnserver[12613]: bind: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: Cannot bind local socket to addr: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: Cannot bind local socket to addr: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: bind: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: bind: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: Cannot bind local socket to addr: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: Cannot bind local socket to addr: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: bind: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: Cannot bind local socket to addr: Cannot assign requested address
Dec 01 03:17:38 host turnserver[12613]: Cannot bind local socket to addr: Cannot assign requested address

also from journalctl:
Dec 01 03:22:22 host turnserver[12862]: 0: : Trying to bind fd 172 to <[::1]:3478>: errno=99
Dec 01 03:22:22 host turnserver[12862]: 0: : Cannot bind TLS/TCP listener socket to addr [::1]:3478
Dec 01 03:22:22 host turnserver[12862]: 0: : Trying to bind TLS/TCP listener socket to addr [::1]:3478, again...
Dec 01 03:22:22 host turnserver[12862]: 0: : Trying to bind fd 143 to <[::1]:3478>: errno=99
Dec 01 03:22:22 host turnserver[12862]: 0: : Cannot bind TLS/TCP listener socket to addr [::1]:3478
Dec 01 03:22:22 host turnserver[12862]: 0: : Trying to bind TLS/TCP listener socket to addr [::1]:3478, again...
Dec 01 03:22:22 host turnserver[12862]: 0: : Trying to bind fd 167 to <[::1]:3478>: errno=99
Dec 01 03:22:22 host turnserver[12862]: 0: : Cannot bind TLS/TCP listener socket to addr [::1]:3478
Dec 01 03:22:22 host turnserver[12862]: 0: : Trying to bind TLS/TCP listener socket to addr [::1]:3478, again...
Dec 01 03:22:22 host turnserver[12862]: 0: : TrCannot bind local socket to addr: Cannot assign requested address

**Comment by mircokam** [comment]
Fresh Install on Debian 12 on Hetzner Cloud works
======================================================================

Thank you for using this script.

root@extranet:~/nextcloud-high-performance-backend-setup-main# systemctl status coturn
● coturn.service - coTURN STUN/TURN Server
     Loaded: loaded (/lib/systemd/system/coturn.service; enabled; preset: enabled)
     Active: active (running) since Sat 2023-12-09 17:57:17 UTC; 19s ago
       Docs: man:coturn(1)
             man:turnadmin(1)
             man:turnserver(1)
   Main PID: 17675 (turnserver)
      Tasks: 7 (limit: 2251)
     Memory: 7.5M
        CPU: 81ms
     CGroup: /system.slice/coturn.service
             └─17675 /usr/bin/turnserver -c /etc/turnserver.conf --pidfile=

Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv4. TLS/SCTP listener opened on : 116.203.199.231:5350
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv4. TLS/TCP listener opened on : 116.203.199.231:5350
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/SCTP listener opened on : 2a01:4f8:c2c:8d4d::1:3478
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/TCP listener opened on : 2a01:4f8:c2c:8d4d::1:3478
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/SCTP listener opened on : 2a01:4f8:c2c:8d4d::1:3479
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/TCP listener opened on : 2a01:4f8:c2c:8d4d::1:3479
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/SCTP listener opened on : 2a01:4f8:c2c:8d4d::1:5349
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/TCP listener opened on : 2a01:4f8:c2c:8d4d::1:5349
Dec 09 17:57:17 extranet turnserver[17675]: 0: : IPv6. TLS/SCTP listener opened on : 2a01:4f8:c2c:8d4d::1:5350
Dec 09 17:57:17 extranet systemd[1]: Started coturn.service - coTURN STUN/TURN Server.
