### ISSUE TITLE
Probleme mit nextcloud talk

### ISSUE THREAD

**Issue by lugau45** [sunweaver/nextcloud-high-performance-backend-setup#133]
Hallo, ich habe mir ja mit Hilfe vom Script hpb installiert. Collabora klappt prima nur bei talk hakt es. Mit Firefox am PC lädt es ewig (geht meistens nicht die Video verbindung) mit chromium geht es schneller. Am Android Gerät geht kein Video, nur Ton. Es läuft also nicht wirklich rund. In der Oberfläche von nextcloud kommt beim einrichten der Server keine Fehler. Wir das mit talk noch was wenn das alles mal an die neuste Version angepasst ist (habe ich hier gelesen wegen Android) oder bleibt das alles so la la. Ich hatte gedacht mit dem hpb klappt das mit talk (wenigstens im Browser am PC) gut.

MfG Marco

**Comment by mircokam** [comment]
Android zeigt kein Video da wir eine neuer Version von dem Coturn Server verwenden. Ich hoffe der Bug wird in der Android App irgendwann gefixt. Im Browser sowie unter IOS funktioniert alles prima.
