### ISSUE TITLE
docserver.domain.com refused to connect

### ISSUE THREAD

**Issue by CloudCoder** [sunweaver/nextcloud-high-performance-backend-setup#137]
Hi,

I installed the HPB and linked it to my Nextcloud OK but I get a "<docserver.domain.com> refused to connect" message when I try to open a presentation in full screen mode?

Everything else works wonderfully.

Any help greatly appreciated.

Thanks

**Comment by mircokam** [comment]
Hello,
i tested it with the last version an here it works perfect.
