### ISSUE TITLE
package 'ttf-mscorefonts-installer' has no installation candidate

### ISSUE THREAD

**Issue by Coolsero** [sunweaver/nextcloud-high-performance-backend-setup#142]
Hallo, 

Ich habe die Installation mit den Script in der Version 1.2.5 versucht, jedoch
hier funktioniert die Installation erst gar nicht, da ich die Fehlermeldung

package 'ttf-mscorefonts-installer' has no installation candidate

erhalte. 

Die Installation mit der Script Version 1.2.3 läuft ohne Probleme durch, jedoch startet am ende der signaling server nicht. 
Es wird dazu nur folgende Fehlermeldung ausgegeben:

nextcloud-spreed-signaling.service - Nextcloud Talk signaling server
     Loaded: loaded
(/lib/systemd/system/nextcloud-spreed-signaling.service; enabled; vendor
preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-02-12 10:11:45
UTC; 33s ago
    Process: 39287
ExecStart=/usr/local/bin/nextcloud-spreed-signaling-server --config
/etc/nextcloud-spreed-signaling/server.conf (code=exited, status=203/EXEC)
   Main PID: 39287 (code=exited, status=203/EXEC)
        CPU: 2ms

Feb 12 10:11:45 hpb systemd[1]: nextcloud-spreed-signaling.service:
Scheduled restart job, restart counter is at 18.
Feb 12 10:11:45 hpb systemd[1]: Stopped Nextcloud Talk signaling server.
Feb 12 10:11:45 hpb systemd[1]: nextcloud-spreed-signaling.service:
Start request repeated too quickly.
Feb 12 10:11:45 hpb systemd[1]: nextcloud-spreed-signaling.service:
Failed with result 'exit-code'.
Feb 12 10:11:45 hpb systemd[1]: Failed to start Nextcloud Talk signaling
server. 

Gruß Markus

**Comment by dzatoah** [comment]
Also das sind zwei getrennte Probleme hier.
Zuerst das eigentliche Problem: `package 'ttf-mscorefonts-installer' has no installation candidate`. Das bedeutet, dass irgendwas schiefgelaufen ist, bei dem Versuch, das `nonfree`-Repo für Debian zu aktivieren. Ich kann dieses Problem nicht reproduzieren, mit einem frischen Debian 12 (zumindest die Hetzner VPS-Variante).

Das zweite Problem ist schätzungsweise mit dem letzten Release gelöst worden. Bitte versuche das Skript immer aktuell zu halten. Mehr siehe hier: https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/129 und #108

**Comment by Coolsero** [comment]
Hallo,

so zum ersten Problem, hier mal ein Auszug aus dem log. 
Die Farge ist welche Quelle hier fehlt ?


Get:1 file:/etc/apt/mirrors/debian.list Mirrorlist [30 B]
Get:2 file:/etc/apt/mirrors/debian-security.list Mirrorlist [39 B]
Hit:3 https://deb.debian.org/debian bookworm InRelease
Hit:4 https://deb.debian.org/debian bookworm-updates InRelease
Hit:5 https://deb.debian.org/debian bookworm-backports InRelease
Hit:7 https://www.collaboraoffice.com/repos/CollaboraOnline/CODE-deb ./ InRelease
Hit:6 https://deb.debian.org/debian-security bookworm-security InRelease
Reading package lists...
Building dependency tree...
Reading state information...
All packages are up to date.
Reading package lists...
Building dependency tree...
Reading state information...
Package ttf-mscorefonts-installer is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-mscorefonts-installer' has no installation candidate

Danke Markus

**Comment by mh-74** [comment]
Probier mal:
echo "deb http://deb.debian.org/debian bookworm contrib non-free" > /etc/apt/sources.list.d/contrib.list

**Comment by dzatoah** [comment]
> Probier mal: echo "deb http://deb.debian.org/debian bookworm contrib non-free" > /etc/apt/sources.list.d/contrib.list

Ja, das ist ein Workaround, aber das löst das Problem an der Wurzel nicht. Deswegen brauche ich das *ganze* Logfile, um analysieren zu können, warum der Aufruf an `apt-add-repository` fehlgeschlagen ist.

**Comment by mircokam** [comment]
Script ist um passendne Befehl erweitert.
