### ISSUE TITLE
Version des HPB wird nicht angezeigt

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#143]
Nach der Installtion,
egal ob aus den Spreed Quellen oder als Deb Paket wird unter den Talk Einstellungen nicht die Verison des Spreed Servers angezeigt.

Es wird folgendes ausgeben: {"nextcloud-spreed-signaling":"Welcome","version":"unreleased"}
Eigentlich sollte hier die Verison aus dem Git angegeben werden.

Das ist bei Herrn Rieger so beschrieben:
https://www.c-rieger.de/nextcloud-hpb-talk-signaling-server/#API

Daniel hat dazu folgendes geschrieben:

_Das ist kein Konfigurationsfehler, sondern irgendwas läuft offenbar schief beim Bauen der Executables (nextcloud-spreed-signaling-server).
Die Version wird beim Bauen via make gesetzt (Auszug aus dem Makefile).
VERSION := $(shell "$(CURDIR)/scripts/get-version.sh")
Die Frage ist: Wie baut ihr das Debian-Paket? Habt ihr dort vielleicht eine Linkeroption vergessen?
INTERNALLDFLAGS := -X main.version=$(VERSION)_

Aber auch wenn wir das aus den Sourcen direkt installierne ist das gleiche Problem vorhanden!

**Comment by dzatoah** [comment]
Das Bauen von `nextcloud-spreed-signaling` ist eigentlich recht einfach: Wir machen unter anderem nichts anderes als die fertige Binary von `https://github.com/strukturag/nextcloud-spreed-signaling/archive/refs/heads/master.tar.gz` herunterzuladen.

Das bedeutet, das ist ein Bug auf Seite von `strukturag/nextcloud-spreed-signaling`.
