### ISSUE TITLE
Nextcloud 28.0.2 Turns scheint ein Problem zu haben

### ISSUE THREAD

**Issue by andre5tz** [sunweaver/nextcloud-high-performance-backend-setup#145]
Hallo,

gestern habe ich die Version 1.2.6 auf einem Hetzner Cloud Server installiert und in Nextcloud eingebunden.

Mit einer Nextcloud 27.1.6 ist beim Turn-Server bei den Einstellungen Turn und Turns und UDP und TCP alles OK.
Mit einer Nextcloud 28.0.2 wird bei dem Test ein Ausrufezeichen angezeigt. Der Test nur mit Turn, ohne "s" ist aber auch OK.

Bei den Protokollen findet sich dann die folgende Fehlermeldung:
`stream_socket_client(): Unable to connect to ssl://nchpb.domain.de:5349 (Connection refused) at /usr/www/users/domain/xxx-xxxxxxxx.de/nextcloud/apps/spreed/lib/Service/CertificateService.php#107`

Es gibt noch weitere ältere Fehlermeldungen die dürften aber nicht den aktuellen nextcloud-high-performance-backend-Server 1.2.6 betreffen.

Gibt es aktuell Probleme mit Nextcloud 28, oder liegt es eher an meiner Installation?

VG
André

P.S.: Vielen Dank an Euch, dass Ihr das Paket bereitstellt.

**Comment by mircokam** [comment]
Hallo Andre,
ich habe beides ( Deb sowie source) nochmal durchinstalliert und mit einer nextcloud 28.0.2 gestestet.  Bei mir werden bei der Einstellung Turn + Turns jeweils grüne Hacken angezeigt. Wo siehtst Du den den Fehler?

Danke Mirco

**Comment by andre5tz** [comment]
Hallo Mirco,

danke für Deine Rückmeldung.

Wenn ich in Nextcloud als Admin eingelogt bin und unter Verwaltung -> Talk beim Turn Server hinten rechts auf das "Test-Icon" klicke, dann wird ein Aisrufezeichen angezeigt.

Anschließend wird dann unter Verwaltung -> Protokollierung die Fehlermeldung angezeigt.
`[PHP] Fehler: stream_socket_client(): Unable to connect to ssl://nc-hpb.domain.de:5349 (Connection refused) at /usr/www/users/domain/xxx-xxxxxxxx.de/nextcloud/apps/spreed/lib/Service/CertificateService.php#107
	GET /ocs/v2.php/apps/spreed/api/v1/certificate/expiration?host=nc-hpb.domain.de:5349
	von 2003:e2:2721:1100:1090:2b7a:6b78:1f52 von Adminxxx um 17.02.2024, 18:51:19
`

Ich kann aber nicht ausschließen, was falsch gemacht zu haben. Zum Beispiel habe ich die Installation an dem Punkt  Build "from source" from source gewählt, vielleicht liegts auch daran? 
Da könnte übrigens noch der Screenshot im Wikki aktualieiert werden, ich hatte die Auswahl ja/nein.

Falls das Problem nur bei mir auftaucht, kannst Du das Issue auch gerne schließen. Gerne helfe ich aber auch, sofern ich kann, Admin Zugang könnte ich auch bereitstellen.

VG
André

**Comment by andre5tz** [comment]
Hier noch die detaillierte Meldung von NC.
`{
  "reqId": "xxxxxxxxxxxxxxxxxxxx",
  "level": 3,
  "time": "2024-02-17T17:51:19+00:00",
  "remoteAddr": "xxxx:xx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx",
  "user": "Admin",
  "app": "PHP",
  "method": "GET",
  "url": "/ocs/v2.php/apps/spreed/api/v1/certificate/expiration?host=nc-hpb.domain.de:5349",
  "message": "stream_socket_client(): Unable to connect to ssl://nc-hpb.domain.de:5349 (Connection refused) at /usr/www/users/domain/xxx-xxxxxxxx.de/nextcloud/apps/spreed/lib/Service/CertificateService.php#107",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0",
  "version": "28.0.2.5",
  "data": {
    "app": "PHP"
  },
  "id": "xxxxxxxxxxxxx"
}`

**Comment by andre5tz** [comment]
Hm... wenn ich bei der TURN-Server-URL den Port nicht mit angebe, dann kommt die grüne Bestätigung und keine Fehlermeldung.
nc-hpb.domain.de:5349 -> nc-hpb.domain.de

**Comment by mircokam** [comment]
Hallo,
ich schließe das ich den Fehler nicht achvollziehen konnte
