### ISSUE TITLE
Vorgeschalteter reverse proxy mit SSL Offloading

### ISSUE THREAD

**Issue by SaimenSays** [sunweaver/nextcloud-high-performance-backend-setup#146]
Wie die Überschrift schon sagt, habe ich einen vorgeschalteten Nginx reverse Proxy auf einem separatem Host. 
Ist es möglich Einstellungen so vorzunehmen, dass der Signaling Server korrekt konfiguriert wird, dieser aber nur auf port 80 lauscht? Ich habe die Installation von letsencrypt abgeschaltet, und dachte damit läuft es. Nginx startet aber wohl nicht weil die Konfiguration nicht vollständig ist.

**Comment by mircokam** [comment]
Da können wir Dir hier leider niccht weiterhelfen.
