### ISSUE TITLE
Multiple Issues with current Script Version

### ISSUE THREAD

**Issue by DPajaziti** [sunweaver/nextcloud-high-performance-backend-setup#150]
Hello Guys,
first of all - thank you for the amazing work you Guys have stuffed into this Project.

I've had my few shares of Headaches in the last 48 Hours, trying to set everything up.
And it would be way too much, to reharse everything what went wrong.

But I'll try my best, to let you guys know of a few things I fixed, shortly after everything ran fine.

1: CoTurn
Has a lot of issues, but most prominently I had to use EXTERNAL IP for the external ip and the LOCAL_IP, 
aswell as Proxy IP had to be 192.x.x.x. IPs (so local ones)

2: Janus:
Does not work, because it sends 20 bytes of data to the STUN Host (which is up and working),
and waits for a reply, but in the meantime it crashes without any errors or anything. Restart doesnt affect it at all.
Only works after commenting the STUN Server out.

3: Signaling Backend:
The Status of the Service was inactive (errored) because of something something restart to quickly.
After trying to start it manually again it worked, but only after killing the pid of lsof 8080 before.

Please excuse any logical Issues, or anything related to bad grammar.
That was just a mindmap, whilst fixing stuff and/or after fixing Stuff.

Can you guys do anything with that? Otherwise we can go into a reset and extensive testing/noting of Issues.

BR, Denis

**Comment by antonygroupware** [comment]
Some thing here on a complete fresh debian installation.

**Comment by antonygroupware** [comment]
> Hello Guys, first of all - thank you for the amazing work you Guys have stuffed into this Project.
> 
> I've had my few shares of Headaches in the last 48 Hours, trying to set everything up. And it would be way too much, to reharse everything what went wrong.
> 
> But I'll try my best, to let you guys know of a few things I fixed, shortly after everything ran fine.
> 
> 1: CoTurn Has a lot of issues, but most prominently I had to use EXTERNAL IP for the external ip and the LOCAL_IP, aswell as Proxy IP had to be 192.x.x.x. IPs (so local ones)
> 
> 2: Janus: Does not work, because it sends 20 bytes of data to the STUN Host (which is up and working), and waits for a reply, but in the meantime it crashes without any errors or anything. Restart doesnt affect it at all. Only works after commenting the STUN Server out.
> 
> 3: Signaling Backend: The Status of the Service was inactive (errored) because of something something restart to quickly. After trying to start it manually again it worked, but only after killing the pid of lsof 8080 before.
> 
> Please excuse any logical Issues, or anything related to bad grammar. That was just a mindmap, whilst fixing stuff and/or after fixing Stuff.
> 
> Can you guys do anything with that? Otherwise we can go into a reset and extensive testing/noting of Issues.
> 
> BR, Denis

Die you get it to work? Im struggling arround and my talk meetings doesnt work at all.

**Comment by mircokam** [comment]
It sounds like that you want to use the script behind a NAT with private ip adress. That will not work!

Requirements

    A server with a publicly accessible IP! (not for systems behind a firewall or NAT with a private address)
    A virtual or physical server with Debian 12 (Bookworm)
    A subdomain for the server on which the script is installer

**Comment by antonygroupware** [comment]
Can you explain why it doesnt work.
The firewall (pfsense) will do a 1to1 forward of "any" protocoll. Including tcp and udp.
I changed the public ip in the coturn config and nextcloud will give green checkmarks on every stun/hpe/... configuration

**Comment by antonygroupware** [comment]
Update: I've tested a vm connected direct to the internet (without nat) and it works like a charm...

**Comment by mircokam** [comment]
Thanks ;-)
