### ISSUE TITLE
Server Audit Meldung beim öffnen von Dateien

### ISSUE THREAD

**Issue by lugau45** [sunweaver/nextcloud-high-performance-backend-setup#151]
Es kommt neuerdings eine Meldung Security Warnung wenn ich eine Datei öffne in der Nextcloud.
Server Audit: The is_admin User propertys is Set
Was bedeutet das für mich? Ich glaube auch das diese meldung erst seit 29.0.2 kommt.

**Comment by mircokam** [comment]
Hallo,
also bei mir kommt da nichts. Ich kann auch nicht nachvollziehen wo das jetzt passiert.
Sorry
