### ISSUE TITLE
Server Meldung beim öffnen vom odt Dokumenten

### ISSUE THREAD

**Issue by lugau45** [sunweaver/nextcloud-high-performance-backend-setup#152]
Es ist eine Einblendung (Check Security Warning) die man öffnen kann wo drin steht The is_admin user prooerty is set.
Ich denke die Meldung kam erst seit der Version 29.0.2. Was hat das zu bedeuten?
MfG
Marco

**Comment by haudamekki** [comment]
https://help.nextcloud.com/t/security-warning-the-is-admin-user-property-is-set/194935

**Comment by dzatoah** [comment]
Seems fixed.

https://github.com/CollaboraOnline/online/pull/9242
https://github.com/CollaboraOnline/online/pull/9229

Closing.
