### ISSUE TITLE
How to Add Additional Allowed Domains After Installation

### ISSUE THREAD

**Issue by JonasPaulino** [sunweaver/nextcloud-high-performance-backend-setup#154]
Hello, how are you? I'm quite new to this, and I would like to add new allowed domains after installation. I added one during the installation: meunextcloud.com, and now I want to add others like nextcloud2.com.br and nextcloud3.com.br.

**Comment by g-work** [comment]
For collabora, it's easy, just add them in the config. For talk I'm looking for a solution, too. Any hints?

**Comment by dzatoah** [comment]
See. #156 

Closing.
