### ISSUE TITLE
Neue Domänen hinzufügen / Add new domains [Zulässige Nextcloud-Domänen]

### ISSUE THREAD

**Issue by JonasPaulino** [sunweaver/nextcloud-high-performance-backend-setup#156]
Hallo, alles in Ordnung? Ich bin sehr neu in diesem Bereich und möchte nach der Installation neue zulässige Domänen hinzufügen. Ich habe während der Installation eines hinzugefügt: meunextcloud.com, und jetzt möchte ich weitere hinzufügen, wie nextcloud2.com.br und nextcloud3.com.br.

**Comment by dzatoah** [comment]
Das ist kein Problem, Sie können einfach das Skript erneut ausführen und dann neue erlaubte Domänen hinzufügen.

Mehrere Nextcloud-Domänen können, durch (mehrere) Kommata "`,`", separiert werden.

**Comment by g-work** [comment]
Sehe ich das richtig, dass dabei aber auch neue secrets generiert werden? Bei 10+ Domains, die auf den Server zugreifen, ist das recht unkomfortabel, insbesondere, wenn man auf den betroffenen Instanzen keinen Admin-Account hat und erst die jeweils Zuständigen kontaktieren muss, um ihnen die Credentials zukommen zu lassen.

**Comment by mircokam** [comment]
Hallo,
ja das ist leider so. Wird sich auch in Zukunft nicht so schnell ändern lassen.
