### ISSUE TITLE
Auswahlweiche Defekt

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#16]
Dei auswahlweiche für Deb und Source funktioniert nicht. Das Script installiert sich nur wenn man vorher die soures einträgt und das Script die beiden Pakete findet.

wget http://packages.sunweavers.net/archive.key \
		-O /etc/apt/trusted.gpg.d/sunweaver-archive-keyring.asc
deb http://packages.sunweavers.net/debian bookworm main

ohne die Einträge bricht das Script ab mit:

Processing triggers for man-db (2.9.4-2) ...
Processing triggers for libc-bin (2.31-13+deb11u3) ...
Updating coolwsd systemplate
Removing old packages…
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package nats-server
E: Unable to locate package nextcloud-spreed-signaling
root@debian-unstable-test:~/nextcloud-high-performance-backend-setup-main# ^C

**Comment by PhilDevProg** [comment]
Fixed by https://github.com/sunweaver/nextcloud-high-performance-backend-setup/commit/f29bb0974b38d4efbf16720415a12e69114e7c13
The problem was that the packages (nats-server, nextcloud-spreed-signaling) weren't installed on your Debian.
