### ISSUE TITLE
Re-install script from scratch with a clean installation?

### ISSUE THREAD

**Issue by ozgurkazancci** [sunweaver/nextcloud-high-performance-backend-setup#160]
Hi and thank you very much for this script, a great effort! Much appreciated.

Under Nextcloud 30.0.2, I get; 

"Error: Running version: 1.2.4-1~bpo12+1.debian; Server needs to be updated to be compatible with this version of Talk"

After checking the **closed Issues** here, you suggested re-installing the script with building packages. So, how to install the script again in a **completely fresh way**?

Is there any way to completely uninstall the packages installed by this script, before installing it again and go with building packages (instead of debian packages, this time) ? I'm asking this to not mess all the server up.

Regards,

Konstantin

**Comment by dzatoah** [comment]
Hey, I'm sorry for the late answer.

Would you kindly provide the link to the closed issue you are referencing?

It should be no problem to just execute the script again and switch from the **official Debian packages**  to **building from sources of upstream**. The script will purge all installed packages from the system (including configuration) if you switch from packages to building from sources.
Maybe you can create a snapshot of your VM and try it out :)

**BUT**

I'd suggest to just reinstall the server and freshly install the *high performance backend* server via this script, like it is intended and advised to do so.

I'll close this issue now in advance :)

Greetings
