### ISSUE TITLE
Don't change signaling secret if already exists

### ISSUE THREAD

**Issue by michel-thomas** [sunweaver/nextcloud-high-performance-backend-setup#161]
I test this wonderful script (many thanks!!).

I notice that secrets in `/etc/nextcloud-spreed-signaling/server.conf` are renewed each time we run the script. But with automation, I launch the script when adding a new domain in nextcloud-backend-x.

Is there a way to fix secrets?
Thanks

**Comment by dzatoah** [comment]
I do not understand your problem, sorry. Could you elaborate further?

**Comment by michel-thomas** [comment]
Yes, sure. And thanks for your quick reply.

I insert this script in an ansible playbook, and relaunching playbook reexecute the script, and each time it changes secrets.

I use a workaround placing a flag to indicate if some changes have been done or not, but ideally this script would check if a domain is already declared and not renew its secret.

ps: the workaround works find. no emergency with this issue.

**Comment by dzatoah** [comment]
Ah yes, this is a known bug. See https://github.com/sunweaver/nextcloud-high-performance-backend-setup/issues/162.
This is probably not that difficult to implement. :)

I'll close this issue, thanks.
