### ISSUE TITLE
Script Fehler Certbot zu häufige Abfrage

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#17]
Cerbot bricht im Script ab obwohl man ausgewählt hat das man das Certifikat nicht erneuern will. Siehe unten. Dies passiert abernur wenn die Certifikate zu oft abgefragt wurden. Sonst läuft es durch.

Step 2: Configuring Certbot
Executing Certbot using arguments: 'certonly --nginx --force-interactive --agree-tos --key-path /etc/letsencrypt/live/test.hase.de/privkey.pem --domains test.hase.de --fullchain-path /etc/letsencrypt/live/test.hase.de/fullchain.pem --email [Hase@hase.de](mailto:hase@hase.de)'…
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Would you be willing, once your first certificate is successfully issued, to
share your email address with the Electronic Frontier Foundation, a founding
partner of the Let's Encrypt project and the non-profit organization that
develops Certbot? We'd like to send you email about our work encrypting the web,
EFF news, campaigns, and ways to support digital freedom.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(Y)es/(N)o:
(Y)es/(N)o: yes
Account registered.
Requesting a certificate for test.hase.de
Performing the following challenges:
http-01 challenge for test.hase.de
Waiting for verification...
Cleaning up challenges
Subscribe to the EFF mailing list (email: [test@hase.de](mailto:test@hase.de)).
We were unable to subscribe you the EFF mailing list because your e-mail address appears to be invalid. You can try again later by visiting https://act.eff.org/.
IMPORTANT NOTES:
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/test.hase.de/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/test.hase.de/privkey.pem
   Your certificate will expire on 2022-11-29. To obtain a new or
   tweaked version of this certificate in the future, simply run
   certbot again. To non-interactively renew *all* of your
   certificates, run "certbot renew"
 - If you like Certbot, please consider supporting our work by:

   Donating to ISRG / Let's Encrypt: https://letsencrypt.org/donate
   Donating to EFF:                    https://eff.org/donate-le

Executing Certbot using arguments: 'renew --force-renewal'…
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/test.hase.de.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Plugins selected: Authenticator nginx, Installer nginx
Renewing an existing certificate for test.hase.de
Failed to renew certificate test.hase.de with error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates (5) already issued for this exact set of domains in the last 168 hours: test.hase.de, retry after 2022-09-01T18:56:04Z: see https://letsencrypt.org/docs/duplicate-certificate-limit/

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/test.hase.de/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
1 renew failure(s), 0 parse failure(s)
Something wen't wrong while starting Certbot.
Maybe the error is in the nextcloud-hpb.conf file (please read the error message above).

**Do you wish to delete this [file:'/etc/nginx/sites-enabled/nextcloud-hbp.conf](file:///'/etc/nginx/sites-enabled/nextcloud-hbp.conf)'? [YyNn]y
rm: cannot remove '/etc/nginx/sites-enabled/nextcloud-hpb.conf': No such file or directory
File got deleted. Please try again now.**

**Comment by PhilDevProg** [comment]
This seems to be a bug of Certbot and not of the script. @sunweaver ?

**Comment by sunweaver** [comment]
Neither. It is a safety measure against DoS by the people running the Let's Encrypt platform.

If you renew a certificate for a certain domain too often, you get blocked for 168 hours (or so) by the signing authority.

Nothing we can do about it and it mostly occurs during testing Let's Encrypt automations. Nothing to worry about for production users.

**Comment by dzatoah** [comment]
You can circumvent this by adding `--break-my-certs` and `--staging` (`--test-certs`) to the certbot parameters in src/setup-certbot.sh. Note that the certs are not trusted by normal configured webbrowsers.
