### ISSUE TITLE
ERROR: Could not find a profile matching 'WWW Full'

### ISSUE THREAD

**Issue by enoch85** [sunweaver/nextcloud-high-performance-backend-setup#18]
Thought, it might be worth trying out. Cool with a pure Debian installer!

Though, fail:
```
Step 2: Configure firewall
Default incoming policy changed to 'deny'
(be sure to update your rules accordingly)
Default outgoing policy changed to 'allow'
(be sure to update your rules accordingly)
Rules updated
Rules updated (v6)
ERROR: Could not find a profile matching 'WWW Full'
```

**Comment by PhilDevProg** [comment]
Which Debian version are you using?

**Comment by sunweaver** [comment]
In ufw: /etc/ufw/applications.d/ufw-webserver, I see:

```
[WWW]
title=Web Server
description=Web server
ports=80/tcp

[WWW Secure]
title=Web Server (HTTPS)
description=Web Server (HTTPS)
ports=443/tcp

[WWW Full]
title=Web Server (HTTP,HTTPS)
description=Web Server (HTTP,HTTPS)
ports=80,443/tcp

[WWW Cache]
title=Web Server (8080)
description=Web Server (8080)
ports=8080/tcp
```

So, in theory this should work (and we haven't spotted that issue so far).

What distro do you use, what version of Debian and ideally what's the version of your ufw package (dpkg -l ufw).

Thanks.

**Comment by sunweaver** [comment]
And, I can't reproduce the above issue:

```
Processing triggers for ufw (0.36.1-4) ...
Rules updated for profile 'OpenSSH'
Rules updated for profile 'WWW Full'
```

@enoch86: Does /etc/ufw/applications.d/ufw-webserver exist on your system?

**Comment by philkonczyk** [comment]
I have the same issue. I solved it by pre-creating the /etc/ufw/applications.d/ufw-webserver file with the included text above.

**Comment by enoch85** [comment]
Maybe reopen this to fix it with a PR then?

**Comment by mircokam** [comment]
Ok, we will check this
Thanks

**Comment by mircokam** [comment]
Hello,
can you please test our new version from the script v 1.2.3.
thanks
