### ISSUE TITLE
nextcloud-spreed-signaling unusable until Debian Unstable has version v0.5.0!

### ISSUE THREAD

**Issue by dzatoah** [sunweaver/nextcloud-high-performance-backend-setup#2]
Until then we need to manually build and run the Signaling server in order to archive a successful Nextcloud Talk conversation.

https://github.com/strukturag/nextcloud-spreed-signaling#building

**Comment by dzatoah** [comment]
It won't be possible for a while to have nextcloud-spreed-signaling 0.5.0 in Debian testing/unstable. Due to build requirement change on etcd >= 3.5.7 which is not in Debian, yet.
So, please identify the fixes introduced in 0.5.0 that we can hopefully cherry-pick to nextcloud-spreed-signaling in Debian's nextcloud-spreed-signaling 0.4.x package.

- Mike

**Comment by dzatoah** [comment]
https://packages.debian.org/search?keywords=nextcloud-spreed-signaling

**Comment by mircokam** [comment]
Es ist etcd >= 3.5.6

**Comment by mircokam** [comment]
Muss durch neues Paket ersetzt werden. Kommt dann nach Debian Backports
