### ISSUE TITLE
Run behind ngnix reverse proxy

### ISSUE THREAD

**Issue by REAPERSbattlecry** [sunweaver/nextcloud-high-performance-backend-setup#20]
Hey, 
is it possible to run the script behind a reverse proxy? In my case I also manage the SSL-certificates with the proxy manager...

**Comment by dzatoah** [comment]
Nginx gets installed by default. It is configured as a reverse proxy for nextcloud-spreed-signaling and collabora. So it handles all of the SSL/HTTPS stuff right out of the box.

SSL certificates are managed by Certbot which will get the certs for your domain from Let's Encrypt. Also right out of the box :)

**Comment by mircokam** [comment]
The Script is more for a complete quick an easy setup. What you want is more special an not the focus of the script.
But if you want you can change it by yourselfe.
Sorry ;-)
