### ISSUE TITLE
Install Script läuft aktuell nicht (coturn patch error)

### ISSUE THREAD

**Issue by play113** [sunweaver/nextcloud-high-performance-backend-setup#24]
...
coturn-master/turndb/testmongosetup.sh
coturn-master/turndb/testredisdbsetup.sh
coturn-master/turndb/testsqldbsetup.sql
Creating patch files…
Applying patches…
error: patch failed: coturn-master/src/client/ns_turn_msg.c:256
error: coturn-master/src/client/ns_turn_msg.c: patch does not apply

**Comment by mircokam** [comment]
Wenn man in src/setup-signaling.sh folgende drei Zeilen entfernt funktioniert es. Wir werden das aber fixen.
Danke

# FIXME: Use here-doc rather than base64 strings…
        #log "Creating patch files…"
        #echo "RnJvbTogTmljaG9sYXMgR3VyaWV2IDxndXJpZXYtbnNAeWEucnU+CkRhdGU6IFRodSwgMDIgSnVuIDIwMjIgMTI6MzQ6MTcgKzAzMDAKU3ViamVjdDogRG8gbm90IGNoZWNrIEZJUFMgMTQwIG1vZGUKIEl0IGlzIG5vdCBhdmFpbGFibGUgaW4gT3BlblNTTCBhcyBwYWNrYWdlZCBpbiBEZWJpYW4uIFRoZSBPUEVOU1NMX0ZJUFMgbWFjcm8KIGFwcGVhcmVkIGluIGFuY2llbnQgT3BlblNTTCBzb3VyY2VzIGJ1dCB3YXMgbmV2ZXIgZGVmaW5lZC4KIGh0dHBzOi8vc291cmNlcy5kZWJpYW4ub3JnL3NyYy9vcGVuc3NsLzEuMS4xbi0wJTJCZGViMTF1Mi9jcnlwdG8vb19maXBzLmMvCgotLS0KIHNyYy9jbGllbnQvbnNfdHVybl9tc2cuYyB8ICAgIDQgKystLQogMSBmaWxlIGNoYW5nZWQsIDIgaW5zZXJ0aW9ucygrKSwgMiBkZWxldGlvbnMoLSkKCi0tLSBhL3NyYy9jbGllbnQvbnNfdHVybl9tc2cuYworKysgYi9zcmMvY2xpZW50L25zX3R1cm5fbXNnLmMKQEAgLTI0NCw3ICsyNDQsNyBAQCBpbnQgc3R1bl9wcm9kdWNlX2ludGVncml0eV9rZXlfc3RyKGNvbnN0CiAJCXVuc2lnbmVkIGludCBrZXlsZW4gPSAwOwogCQlFVlBfTURfQ1RYIGN0eDsKIAkJRVZQX01EX0NUWF9pbml0KCZjdHgpOwotI2lmIGRlZmluZWQgRVZQX01EX0NUWF9GTEFHX05PTl9GSVBTX0FMTE9XICYmICFkZWZpbmVkKExJQlJFU1NMX1ZFUlNJT05fTlVNQkVSKQorI2lmZGVmIE9QRU5TU0xfRklQUwogCQlpZiAoRklQU19tb2RlKCkpIHsKIAkJCUVWUF9NRF9DVFhfc2V0X2ZsYWdzKCZjdHgsRVZQX01EX0NUWF9GTEFHX05PTl9GSVBTX0FMTE9XKTsKIAkJfQpAQCAtMjU2LDcgKzI1Niw3IEBAIGludCBzdHVuX3Byb2R1Y2VfaW50ZWdyaXR5X2tleV9zdHIoY29uc3QKICNlbHNlCiAJCXVuc2lnbmVkIGludCBrZXlsZW4gPSAwOwogCQlFVlBfTURfQ1RYICpjdHggPSBFVlBfTURfQ1RYX25ldygpOwotI2lmIGRlZmluZWQgRVZQX01EX0NUWF9GTEFHX05PTl9GSVBTX0FMTE9XICYmICEgZGVmaW5lZChMSUJSRVNTTF9WRVJTSU9OX05VTUJFUikKKyNpZmRlZiBPUEVOU1NMX0ZJUFMKIAkJaWYgKEZJUFNfbW9kZSgpKSB7CiAJCQlFVlBfTURfQ1RYX3NldF9mbGFncyhjdHgsIEVWUF9NRF9DVFhfRkxBR19OT05fRklQU19BTExPVyk7CiAJCX0K" | base64 -d - >No-FIPS-140-mode.patch

**Comment by mircokam** [comment]
Is fixed

**Comment by play113** [comment]
Danke für die schnelle Reaktion ... läuft wieder ;)
