### ISSUE TITLE
Beim Start von Janus muss coturn erreichbar sein

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#25]
Wenn Janus beim Systemstart geladen wird, ist u.U. der coturn-Dienst noch nicht am Laufen. In diesem Fall steigt Janus komplett aus (kein Retry, o.ä.). Daher muss Janus nach dem coturn-Dienst gestartet werden.

Mögliche Lösung: Per cron 15 Sek nach Systemstart den Janus-Dienst einmal neu starten. Hier ist dann sicher gestellt, dass coturn bereits läuft. (DecaTec)

**Comment by dzatoah** [comment]
> Mögliche Lösung: Per cron 15 Sek nach Systemstart den Janus-Dienst einmal neu starten. Hier ist dann sicher gestellt, dass coturn bereits läuft. (DecaTec)
Das klingt gut.

Man könnte sonst auch im Janus `.service` den Coturn-Dienst als dependency setzen und vor dem Start ein `sleep 15s` ausführen.
