### ISSUE TITLE
Collabora: Welcome Screen

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#26]
Beim ersten Öffnen wird immer der Welcome Screen von Collabora angezeigt!

Dies kann in der coolwsd.xml deaktiviert werden:

<welcome> <enable type="bool" desc="Controls whether the welcome screen should be shown to the users on new install and updates." default="false">false</enable> <enable_button type="bool" desc="Controls whether the welcome screen should have an explanatory button instead of an X button to close the dialog." default="false">false</enable_button> <path desc="Path to 'welcome-$lang.html' files served on first start or when the version changes. When empty, defaults to the Release notes." type="path" relative="true" default="loleaflet/welcome> </welcome>

**Comment by dzatoah** [comment]
Ich finde dazu keine Dokumentation und weder im Debian-Paket `coolwsd` noch im git unter
https://github.com/CollaboraOnline/online/blob/master/coolwsd.xml.in
gibt es dazu etwas zu finden. 

Ist das vielleicht ein altes Feature, welches herausgenommen wurde?

**Comment by dzatoah** [comment]
Hier findet sich dein Code-Schnipsel:
https://github.com/CollaboraOnline/online/commit/c550a206e8a25780aa2fd649f558b2415482dbee

Dieser Schnipsel wurde allerdings entfernt...

Es gibt Referenzen zwischen welcome.enable und dem Home-Mode... Also vielleicht sollten wir testen das hier auf true zu stellen:
```
<home_mode>
    <enable desc="Enable more configuration options for home users" type="bool" default="false">false</enable>
</home_mode>
```

**Comment by DecaTec** [comment]
@dzatoah Nein, leider auch nicht.
Am besten mal bei einer erfolgten Installation testen.
Wichtig ist hier nur, dass ein Browser das erste Mal "Kontakt" zu Collabora hat glaube ich (also private Mode, o.ä. verwenden).

**Comment by mircokam** [comment]
Den Screen hab ich jetzt schon lange nicht mehr gesehen. Es scheint zu funktionieren.
