### ISSUE TITLE
Nextcloud: Signaling URL in NC-Admin-UI

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#29]
Unwichtig für das Projekt selbst (betrifft NC Config), nur ein Reminder

War so angegeben:

wss://signaling.testserver.de/standalone-signaling

Sollte aber so angegeben werden, wird ja über nginx "geroutet":

https://signaling.testserver.de/standalone-signaling

**Comment by dzatoah** [comment]
Aber Nginx routet ja auch websockets auf Port 80. Daher sollte doch wss://signaling.testserver.de/standalone-signaling schon richtig sein, oder nicht?

**Comment by DecaTec** [comment]
Ich mache die SSL-Terminierung immer am nginx. Hat einfach den Hintergrund, dass man die Zertifikate nicht in jedes Programm einzeln hinein konfigurieren muss, sondern dass dies alles am nginx passiert.

Wenn man wss am Signaling nutzen würde, dann würden die Zertifikate dort liegen. Da finde ich den Zugriff über HTTPS/nginx deutlich einfacher von der Konfiguration.

**Comment by dzatoah** [comment]
Das wurde doch von dir jetzt hinzugefügt, oder? @mircokam
