### ISSUE TITLE
Webserver/Zertifikate: DH-Params fehlen

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#33]
Es werden keine DH-Params genutzt.
Diese sollten mit 4096 Bit erzeugt und genutzt werden.

Hinweis: Die Erzeugung dieser DH-Params kann u.U. eine Weile dauern und wird den Installationsprozess verzögern.

Ggf. "vorgefertigte" DH-Params mit den Skripten ausliefern und ein Skript beifügen, welches der Admin dann manuell nach Abschluss der Installation ausführen kann/soll.

**Comment by mircokam** [comment]
Ergänzung: Beim coturn werden die DH-Params bereits erzeugt (4096 Bit).

[nextcloud-high-performance-backend-setup/src/setup-signaling.sh](https://github.com/DecaTec-IT/nextcloud-high-performance-backend-setup/blob/01c482bf6b8ace64e5b32b4c0561c8ac1e8f66da/src/setup-signaling.sh#L251)

Line 251 in [01c482b](https://github.com/DecaTec-IT/nextcloud-high-performance-backend-setup/commit/01c482bf6b8ace64e5b32b4c0561c8ac1e8f66da)
 is_dry_run || openssl dhparam -dsaparam -out "$COTURN_DIR/dhp.pem" 4096 

Diese können dann auch für nginx genutzt werden.

**Comment by dzatoah** [comment]
e.g. `ssl_dhparam "$COTURN_DIR/dhp.pem"` in https://github.com/sunweaver/nextcloud-high-performance-backend-setup/blob/01c482bf6b8ace64e5b32b4c0561c8ac1e8f66da/data/nginx/nextcloud-hpb.conf#L35

**Comment by DecaTec** [comment]
Gibt es einen Grund für diese Reihenfolge:
```
if [ "$SHOULD_INSTALL_UFW" = true ]; then install_ufw; else
log "Won't install UFW."
fi
if [ "$SHOULD_INSTALL_COLLABORA" = true ]; then install_collabora; else
log "Won't install Collabora."
fi
if [ "$SHOULD_INSTALL_SIGNALING" = true ]; then install_signaling; else
log "Won't install Signaling."
fi
if [ "$SHOULD_INSTALL_CERTBOT" = true ]; then install_certbot; else
log "Won't install Certbot."
fi
if [ "$SHOULD_INSTALL_NGINX" = true ]; then install_nginx; else
log "Won't install Nginx."
fi
if [ "$SHOULD_INSTALL_UNATTENDEDUPGRADES" = true ]; then install_unattendedupgrades; else
log "Won't install unattended upgrades."
fi
```

Ich würde hier ufw, certbot, nginx, signaling, office (in dieser Reihenfolge) installieren.

Das generieren der DHParams würde dann im nginx-Setup passieren. 
Speicht hier etwas dagegen?
