### ISSUE TITLE
coturn: Nicht from Source bauen, sondern Paketquellen verwenden

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#37]
coturn kann einfach über apt install coturn installiert werden.

Die Software wird nicht häufig aktualisiert und neue Features dürften so gut wie nie hinzukommen. Daher ist das Bauen per Source eher umständlich ohne zusätzlichen Mehrwert.

Oder gibt es bestimmte Features, die definitiv benötigt werden und in der coturn-Version der Debian-Paketquellen nicht vorhanden sind?

**Comment by dzatoah** [comment]
Der Grund ist, dass coturn noch die Version `4.5.2-3` in den Debian 11 Paketquellen hat und es in dieser Version einen Bug gibt der coturn abstürzen lässt, wenn jemand sich mithilfe von Signaling verbinden möchte.

Ich hab dann diesen Patch applied und dann ging es. https://github.com/coturn/coturn/pull/895
Der ist auch mittlerweile in den master gemergt worden.

**Comment by dzatoah** [comment]
Ich würde sagen, wir schließen dieses Ticket erstmal.
