### ISSUE TITLE
coturn/port 443

### ISSUE THREAD

**Issue by DecaTec** [sunweaver/nextcloud-high-performance-backend-setup#44]
coturn sollte wegen max. Kompatibilität auf Port 443 laufen, dieser Port ist allerdings schon von nginx belegt.

## Idee
* Vorschalten eines HAProxy (port 80/443 im **tcp mode**)
* nginx auf alternativen Ports setzen (z.B. 8282/4433)
* Redirect HAProxy Port 80 -> nginx Port 8282 und HAProxy Port 443 (**Signaling-Domain**) -> nginx Port 4433
* SSL-Terminierung (Web/Signaling-Domain) am nginx
* Redirect HAProxy Port 443 (**coturn-Domain**) -> coturn Port 5349
* SSL-Terminierung (STUN/TURN/coturn-Domain) am coturn

## Voraussetzung
* Zweite Domain (coturn-Domain), die auf den gleichen Server verweist.

**Comment by dzatoah** [comment]
Ja, die Idee die Kompatibilität zu erhöhen finde ich gut. Ich finde nur doof, dass man dann für zukünftige Versionen vom HPB-Skripts dann immer zwei (Sub)Domains bräuchte. Wir könnten das ganze Konstrukt optional zuschaltbar machen. Das würde dann aber die Komplexität vom Skript erhöhen.

Andererseits muss man ja sowieso fürs HPB eine (Sub)Domain hinzufügen und meistens ist das Hinzufügen einer weiteren schnell gemacht.

@mircokam was hältst du davon?

**Comment by mircokam** [comment]
Ja denk ich auch. Eine zweite Subdomain sollte kein so großer Aufwand sein. Wenn es dann mit jeder Firewall funktioniert wäre das denke ich den Aufwand wert. :-)

**Comment by sunweaver** [comment]
```
# this is jitsi-meet nginx module configuration
# this forward all http traffic to the nginx virtual host port
# and the rest to the turn server
#
# Multiplexing based on ALPN is DEPRECATED. ALPN does not play well with websockets on some browsers and reverse proxies.
# To migrate away from using it read: https://jitsi.org/multiplexing-to-bridge-ws-howto
# This file will be removed at some point and if deployment is still using it, will break.
#
stream {
    upstream web {
        server 127.0.0.1:4444;
    }
    upstream turn {
        server 127.0.0.1:5349;
    }
    # since 1.13.10
    map $ssl_preread_alpn_protocols $upstream {
        ~\bh2\b         web;
        ~\bhttp/1\.     web;
        default         turn;
    }

    server {
        listen 443;
        listen [::]:443;

        # since 1.11.5
        ssl_preread on;
        proxy_pass $upstream;

        # Increase buffer to serve video
        proxy_buffer_size 10m;
    }
}
# Taken from Jitsi's /etc/nginx/conf.d/60-jitsi-meet.conf (END)
```

**Comment by DecaTec** [comment]
@sunweaver Das war mal bei Jitsi die empfohlene nginx-Config. Hat aber leider meiner Erfahrung nach nie gut funktioniert. Daher entspricht das mittlerweile auch nicht mehr der offiziellen Empfehlung von Jitsi.

**Comment by mircokam** [comment]
I close this.
