### ISSUE TITLE
Collabora Update funktioniert nicht nach update

### ISSUE THREAD

**Issue by mircokam** [sunweaver/nextcloud-high-performance-backend-setup#52]
Wenn man Collbora Office aktualisiert, muss man darauf achten, dass die Config nicht überschrieben wird.

apt update & apt upgrade  -> Dann fragt er ob er die Konfig überschreiben soll! Dann muss man "nein" wählen.

Es wäre schön, wenn es gleich so eingestellt wäre, dass sich Collabora Office mit über die UnattendedUpgrades aktualisiert und die Config nicht überschrieben wird.

**Comment by dzatoah** [comment]
Momentan wird Collabora gar nicht geupgraded.
Dafür müssen wir die unattended-upgrades für Collabora erst freischalten mit:

unattended-Upgrade::Origins-Pattern {
    "site=www.collaboraoffice.com";
}
in '/etc/apt/apt.conf.d/50unattended-upgrades'

Die configs werden standardmäßig nicht überschrieben. Das muss der Nutzer selbst machen. Bzw. wenn es kein unattended-upgrade ist sondern ein manuelles, dann kann man in der Konsole während des upgrades auswählen was passieren soll.
