### ISSUE TITLE
MSMTP: msmtp sends e-mail to 'root'. literally.

### ISSUE THREAD

**Issue by dzatoah** [sunweaver/nextcloud-high-performance-backend-setup#61]
Step 5: Test msmtp configuration
msmtp: recipient address root not accepted by the server
msmtp: server message: 501 <root>: recipient address must contain a domain
msmtp: could not send mail (account [xxxx](mailto:xxxx) from /etc/msmtprc)
root@signaling:~/nextcloud-high-performance-backend-setup-pr-8-add-msmtp-setup#

**Comment by mircokam** [comment]
Neues System gleicher Abbruch:

Replacing '<EMAIL_SERVER_PORT>' with '587'…

Step 4: Deploy msmtp configuration
Deploying /etc/aliases
Deploying /etc/msmtprc

Step 5: Test msmtp configuration
msmtp: recipient address root not accepted by the server
msmtp: server message: 501 <root>: recipient address must contain a domain
msmtp: could not send mail (account [hase@hase.de](mailto:it@rohloff.de) from /etc/msmtprc)
root@testsig:~/nextcloud-high-performance-backend-setup-main#
