### ISSUE TITLE
Failing install on Debian 11

### ISSUE THREAD

**Issue by bossey1** [sunweaver/nextcloud-high-performance-backend-setup#70]
on a fresh install of Debian 11  I get errors.

<#uname-a>
4.19.0 #1 SMP Thu Sep 23 18:26:47 MSK 2021 x86_64 GNU/Linux

<# lsb_release -a>
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye

I am getting this error when trying to install following the English instructions.

Nextcloud HPB setup script version: 1.1.1 
Checking for packages availability…
E: No packages found
Package 'nextcloud-spreed-signaling' is NOT available.
No settings file specified using defaults or asking user for input.
Unsupported service ./setup-nextcloud-hpb.sh:!

**Comment by PhilDevProg** [comment]
Which English instructions do you mean?

**Comment by dzatoah** [comment]
`
Unsupported service ./setup-nextcloud-hpb.sh:!` something is fundamentally broken here.

Are you sure you are using *bash* as a shell? Why is your kernel so old?
Can you please modify the file './setup-nextcloud-hpb.sh' and add a 'set -x' right under the line 3 'set -eo pipefail'?
This will spam your console with a lot of debug messages but we are just interested in the last few lines before its crashing. Thanks :)

**Comment by mircokam** [comment]
Hello,
you can use our latest version:
https://github.com/sunweaver/nextcloud-high-performance-backend-setup/releases/tag/1.2

**Comment by bossey1** [comment]
> Hello, you can use our latest version: https://github.com/sunweaver/nextcloud-high-performance-backend-setup/releases/tag/1.2

Thanks.  I get the same result.

**Comment by bossey1** [comment]
> ` Unsupported service ./setup-nextcloud-hpb.sh:!` something is fundamentally broken here.
> 
> Are you sure you are using _bash_ as a shell? Why is your kernel so old? Can you please modify the file './setup-nextcloud-hpb.sh' and add a 'set -x' right under the line 3 'set -eo pipefail'? This will spam your console with a lot of debug messages but we are just interested in the last few lines before its crashing. Thanks :)

It's a VPS and upon first install that is the kernel installed.
I made the entry and got more feedback as you suggested. Pls see below:

# ./setup-nextcloud-hpb.sh 
+ DRY_RUN=false
+ UNATTENTED_INSTALL=false
+ NEXTCLOUD_SERVER_FQDNS=
+ SERVER_FQDN=
+ SSL_CERT_PATH_RSA=
+ SSL_CERT_KEY_PATH_RSA=
+ SSL_CHAIN_PATH_RSA=
+ SSL_CERT_PATH_ECDSA=
+ SSL_CERT_KEY_PATH_ECDSA=
+ SSL_CHAIN_PATH_ECDSA=
+ DHPARAM_PATH=
++ date +%Y-%m-%dT%H:%M:%SZ
+ LOGFILE_PATH=setup-nextcloud-hpb-2022-11-28T17:50:46Z.log
+ TMP_DIR_PATH=./tmp
+ SECRETS_FILE_PATH=
+ EMAIL_USER_ADDRESS=
+ EMAIL_USER_PASSWORD=
+ EMAIL_USER_USERNAME=
+ EMAIL_SERVER_HOST=
+ EMAIL_SERVER_PORT=
+ DISABLE_SSH_SERVER=false
+ SIGNALING_BUILD_FROM_SOURCES=
++ tr '\n' ' '
++ head -n 1
++ cat VERSION
+ SETUP_VERSION='1.2 '
+ main ''
+ log 'Nextcloud HPB setup script version: 1.2 '
+ tee -a setup-nextcloud-hpb-2022-11-28T17:50:46Z.log
+ echo -e 'Nextcloud HPB setup script version: 1.2 '
Nextcloud HPB setup script version: 1.2 
+ check_root_perm
++ id -u
+ [[ 0 -ne 0 ]]
+ check_debian_system
+ '[' -s /etc/debian_version ']'
++ cat /etc/debian_version
+ DEBIAN_VERSION=11.5
+ [[ 11.5 = \b\o\o\k\w\o\r\m\/\s\i\d ]]
+ [[ 11.5 =~ [0-9] ]]
++ grep -o -E '[0-9][0-9]'
++ echo 11.5
+ DEBIAN_MAJOR_VERSION=11
+ check_available_signaling_packages
+ log 'Checking for packages availability…'
+ tee -a setup-nextcloud-hpb-2022-11-28T17:50:46Z.log
+ echo -e 'Checking for packages availability…'
Checking for packages availability…
+ apt-cache show nextcloud-spreed-signaling
E: No packages found
+ log 'Package '\''nextcloud-spreed-signaling'\'' is NOT available.'
+ tee -a setup-nextcloud-hpb-2022-11-28T17:50:46Z.log
+ echo -e 'Package '\''nextcloud-spreed-signaling'\'' is NOT available.'
Package 'nextcloud-spreed-signaling' is NOT available.
+ return 1
+ SIGNALING_PACKAGES_AVAILABLE=false
+ SETTINGS_FILE=
+ '[' -s '' ']'
+ log 'No settings file specified using defaults or asking user for input.'
+ tee -a setup-nextcloud-hpb-2022-11-28T17:50:46Z.log
+ echo -e 'No settings file specified using defaults or asking user for input.'
No settings file specified using defaults or asking user for input.
+ '[' false '!=' true ']'
+ SHOULD_INSTALL_UFW=false
+ SHOULD_INSTALL_COLLABORA=false
+ SHOULD_INSTALL_SIGNALING=false
+ SHOULD_INSTALL_CERTBOT=false
+ SHOULD_INSTALL_NGINX=false
+ SHOULD_INSTALL_UNATTENDEDUPGRADES=false
+ SHOULD_INSTALL_MSMTP=false
++ whiptail --title 'Select services' --separate-output --checklist 'Use the space bar key to select/deselect the services you want to install.\n\nThe following services/packages will also be installed: Certbot Nginx ssl-cert ufw unattended-upgrades' 15 90 2 1 'Install Collabora (coolwsd, code-brand)' ON 2 'Install Signaling (nats-server, coturn, janus, nextcloud-spreed-signaling)' ON
++ true
+ CHOICES='./setup-nextcloud-hpb.sh: line 484: whiptail: command not found'
+ '[' -z './setup-nextcloud-hpb.sh: line 484: whiptail: command not found' ']'
+ for CHOICE in $CHOICES
+ case "$CHOICE" in
+ log 'Unsupported service ./setup-nextcloud-hpb.sh:!'
+ tee -a setup-nextcloud-hpb-2022-11-28T17:50:46Z.log
+ echo -e 'Unsupported service ./setup-nextcloud-hpb.sh:!'
Unsupported service ./setup-nextcloud-hpb.sh:!
+ exit 1

Shell being used...

# ps -p $$
    PID TTY          TIME CMD
  30543 pts/1    00:00:00 bash

**Comment by bossey1** [comment]
> Which English instructions do you mean?

README_en.md

**Comment by dzatoah** [comment]
I'm going to reopen this since it won't be fixed by just upgrading.

`'[' -z './setup-nextcloud-hpb.sh: line 484: whiptail: command not found' ']'`

Thats probably the failure here. Please ensure whiptail is installed. `sudo apt install whiptail`  
This should fix your problem :)

Sorry for asking but what is a VPS? :)

**Comment by bossey1** [comment]
> I'm going to reopen this since it won't be fixed by just upgrading.
> 
> Sorry for asking but what is a VPS? :)
> 
> `'[' -z './setup-nextcloud-hpb.sh: line 484: whiptail: command not found' ']'`
> 
> Thats probably the failure here. Please ensure whiptail is installed. `sudo apt install whiptail` This should fix your problem :)
> 
> We probably want to check for the whiptail dependency even though its installed on most systems already and I really really wonder why it isn't the case here. Whiptail is being used by dpkg and apt a lot. So why it is missing? :D

Hi VPS is Virtual Private Server ;-)

I upgraded the kernel to 5.18 but that in itself didn't help.
You were right. whiptail wasn't installed.  It may not be a default install in Bullseye.
Yes installation started after installing whiptail.

Yes It would help many who may come across this if that dependency is checked for.

Thank you! :+1: 

Is there somewhere I could ask questions without filing issues? :-}

**Comment by dzatoah** [comment]
Ok, I'm glad I could help. Closing this issue now then.

> Is there somewhere I could ask questions without filing issues? :-}
We don't have any other communication channels atm.
Mh, my personal favorite option would be that you just open tickets for questions which are unanswered by the Wiki. The wiki should be updated then, with a reference to the ticket.

**Comment by bossey1** [comment]
> Ok, I'm glad I could help. Closing this issue now then.
> 
> > Is there somewhere I could ask questions without filing issues? :-}
> 
> We don't have any other communication channels atm. Mh, my personal favorite option would be that you just open tickets for questions which are unanswered by the Wiki. The wiki should be updated then, with a reference to the ticket.

Yes I'm very happy for it to be closed.  Thank you again.
