### ISSUE TITLE
The install presets Openssh to port 22 preventing remote ssh login for systems with other ssh port settings preconfigured

### ISSUE THREAD

**Issue by bossey1** [sunweaver/nextcloud-high-performance-backend-setup#80]
If ssh is previously configured the installation then after reboot one can no longer ssh into the machine. 
For example I found that because my normal ssh port setting isn't the default port 22, the ufw default setting for openssh at port 22 prevented remote login.  Perhaps a prompt to set ssh port may prevent this from happening or at least a warning about it.

**Comment by mircokam** [comment]
Hello,
the normal ssh port is 22 an we do not block this port after reboot or with the ufw firewall. In the script you can deactivate ssh login. If you want the ssh port to change you can do it easy in the config. I think it is not necessary to have a own promt for this:

https://www.ionos.com/help/server-cloud-infrastructure/getting-started/important-security-information-for-your-server/changing-the-default-ssh-port/

If you want to use ssh, i think it is better to have a second firewall in front of the server to block the ssh port complete. Only to change the 22 port is not saver

**Comment by bossey1** [comment]
Hi thanks for the reply.
Your points are all valid but my issue is that many people do not use the standard port 22 as best practice.
Deactivating SSH on a remote VPS does not make for easy administration.
My point is that a reboot after install could end in a situation were you lose access. So a warning out note during a phase of the install that you should check and open your port in ufw, would prevent potential heartache.
I'm merely drawing attention to it so possibly it could simply be in the preinstall notes. 😌

⁣Get BlueMail for Android ​
