### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by tm-berlin** [sunweaver/nextcloud-high-performance-backend-setup#84]
Hi,

Installation on Debian 11 was error-free. 

Nextcloud then reports "Error: The server responded with: 502" for the signing server. In the error log:
2023/02/20 11:52:51 [error] 368#368: *163 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XXX.XXX.XX, server: thpb1.nimmerland.de, request: "GET /standalone-signaling/ HTTP/1.1", upstream: "http://127.0.0.1:8080/", host: "thpb1.XXX.de".

Collabora and Coturn are running perfectly.

BTW is the Collabora of this installation also limited to ten users at the same time?

Thanks a lot for the script. Thomas

**Comment by mircokam** [comment]
Hello,
can you please test our new version from the script V1.2.3
thanks

**Comment by tm-berlin** [comment]
> Hello, can you please test our new version from the script V1.2.3 thanks
Installation has now been completed without errors. The connections are made correctly. 

Thank you for your work!
