### ISSUE TITLE
Collabora user limit

### ISSUE THREAD

**Issue by tquest1** [sunweaver/nextcloud-high-performance-backend-setup#85]
It is mentioned in the instructions that ther is a 20 user limit on this projects Collabora:

_Please note that Collabora Office in this version is limited to 20 users working simultaneously._

Is this due to a limit from Debian? In the Collabora forums it is stated:

[There are no limitations of documents / connections in CODE anymore.](https://forum.collaboraonline.com/t/code-docker-limitations/810/2)

**Comment by mircokam** [comment]
Ok thanks,
maybe my info ist to old.
i remove that from the wiki. 
https://help.nextcloud.com/t/are-there-any-limits-when-using-the-free-version-of-nextcloud-office-collabora-code/142722
