### ISSUE TITLE
Cannot bind TLS/TCP bind: Cannot assign requested address Cannot bind local socket to addr: Cannot assign requested address

### ISSUE THREAD

**Issue by tomassplatch** [sunweaver/nextcloud-high-performance-backend-setup#86]
Hello, thanks for the script. I installed it on a custom Debian 11 image on the Oracle Cloud virtual server. The script ran fine, towards the end I got this message:

"...janus.service failed because the control process exited with error code. See "systemctl status janus.service" and "journalctl -xe" for details. Something went wrong while enabling/starting service 'janus'…"

The journal

turnserver: INFO: Trying to bind DTLS/UDP listener socket to addr 141.145.205.80:3478, again...
turnserver: WARNING: Trying to bind fd 24 to <_my.public.ip_:3478>: errno=99
turnserver: WARNING: Cannot bind TLS/TCP listener socket to addr _my.public.ip_:3478

turnserver: bind: Cannot assign requested address
turnserver: Cannot bind local socket to addr: Cannot assign requested address

Is it a problem of opening ports through Ingress Rules of the VNC network on the cloud console?

**Comment by mircokam** [comment]
Hello,
can you please test our new version from the Script v1.2.3
Thanks

**Comment by tomassplatch** [comment]
Thanks, thank you very much for your reply, sadly, the same result.

**Comment by mircokam** [comment]
Maybe it is a problem with the oracle vm system. We tested the image here with normal Debian 11 images on hetzner cloud server an it works fine.
Sorry i have no idea.
