### ISSUE TITLE
letsencrypt challenge problem

### ISSUE THREAD

**Issue by ozgiray1** [sunweaver/nextcloud-high-performance-backend-setup#96]
I am encountering the following error in the letsencrypt ssl creation step during installation. My DNS record is working. Displaying nginx page with fqdn. Can you help me? thanks.
----------------------------------------------------------------------------------
Step 2: Configuring Certbot
Executing Certbot using arguments: 'certonly --nginx --force-interactive --agree-tos --key-path /etc/letsencrypt/live/nchpb.xx.gov.tr-rsa/privkey.pem --domains nchpb.xx.gov.tr --fullchain-path /etc/letsencrypt/live/nchpb.x.tr-rsa/fullchain.pem --email johndoe@example.com --rsa-key-size 4096 --cert-name nchpb.xx.gov.tr-rsa --chain-path /etc/letsencrypt/live/nchpb.xx.gov.tr-rsa/chain.pem'…
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator nginx, Installer nginx
Requesting a certificate for nchpb.xx.gov.tr
Performing the following challenges:
http-01 challenge for nchpb.xx.gov.tr
Waiting for verification...
Challenge failed for domain nchpb.xx.gov.tr
http-01 challenge for nchpb.xx.gov.tr
Cleaning up challenges
Some challenges have failed.
IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: nchpb.xx.gov.tr
   Type:   unauthorized
   Detail: 212.x.x.x: Invalid response from
   http://nchpb.xx.gov.tr/.well-known/acme-challenge/LqduDQLLADZ85OYisL03If-Nf3cbcZCFqcnIv0yXSHE:
   404

   To fix these errors, please make sure that your domain name was
   entered correctly and the DNS A/AAAA record(s) for that domain
   contain(s) the right IP address.
Something wen't wrong while starting Certbot.
Maybe the error is in the nextcloud-hpb.conf file (please read the error message above).

Do you wish to delete this file:'/etc/nginx/sites-enabled/nextcloud-hbp.conf'? [YyNn]n

**Comment by mircokam** [comment]
Did you enter your domain name correctly? Does the DNS A/AAAA record(s) of that domain contain the right IP?
Your server has a public IP and isn't behind a Firewall or a NAT, right?

**Comment by ozgiray1** [comment]
Yes. Definitely. All the settings you mentioned are done.

**Comment by PhilDevProg** [comment]
And your server has a public IP and isn't behind a Firewall or a NAT?

**Comment by ozgiray1** [comment]
Yes. 80 and 443 nat redirections were made.

**Comment by PhilDevProg** [comment]
This script is NOT made for and NOT intended to be used in situations with a NAT.

**Comment by ozgiray1** [comment]
I know what the command is intended for. My server wants to verify my domain name to generate certificate. however, the method he uses is wrong and the txt content he wants changes every time. Are you sure you understand my problem?

**Comment by PhilDevProg** [comment]
Hmm, not really but as I said above, the script doesn't support and won't support NAT and you said that your server uses NAT so please use this script without a NAT.

**Comment by ozgiray1** [comment]
That's how Certbot will work. How will it verify the domain? any idea?

**Comment by ozgiray1** [comment]
resolved.

**Comment by pgabrys94** [comment]
> resolved.

could you provide some details? im also behind NAT with port forwarding pointing to nginx-reverse-proxy, which redirects both http and https to hpbe (it needs more configuration, but for certbot it should be more than enough).
