### ISSUE TITLE
Janus & Nginx failed

### ISSUE THREAD

**Issue by uruzFR** [sunweaver/nextcloud-high-performance-backend-setup#97]
### Hello !

I installed Debian recently and followed the guide step by step to run the script that comes at the end of the installation, but I encountered some errors :

```
Every installation completed.
Enabling and restarting services…
Enabling and restarting service 'ufw'…
Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ufw
Enabling and restarting service 'coturn'…
Created symlink /etc/systemd/system/multi-user.target.wants/coturn.service → /lib/systemd/system/coturn.service.
Enabling and restarting service 'nats-server'…
Created symlink /etc/systemd/system/multi-user.target.wants/nats-server.service → /lib/systemd/system/nats-server.service.
Enabling and restarting service 'nextcloud-spreed-signaling'…
Created symlink /etc/systemd/system/multi-user.target.wants/nextcloud-spreed-signaling.service → /lib/systemd/system/nextcloud-spreed-signaling.service.
Enabling and restarting service 'janus'…
Synchronizing state of janus.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable janus
**Job for janus.service failed because the control process exited with error code.**
See "systemctl status janus.service" and "journalctl -xe" for details.
Something went wrong while enabling/starting service 'janus'…
Enabling and restarting service 'nginx'…
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
**Job for nginx.service failed because the control process exited with error code.**
See "systemctl status nginx.service" and "journalctl -xe" for details.
Something went wrong while enabling/starting service 'nginx'…
```

As you can see nginx and janus had a mistake, I don’t know where it comes I was going to keep looking on my side but I’m ready if you have a solution !
**Thank you**

**Comment by uruzFR** [comment]
**NGINX Status**

● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-04-12 14:25:57 CEST; 40min ago
       Docs: man:nginx(8)
    Process: 16640 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=1/FAILURE)
        CPU: 16ms

avril 12 14:25:57 debian systemd[1]: Starting A high performance web server and a reverse proxy server...
avril 12 14:25:57 debian nginx[16640]: nginx: [emerg] open() "/etc/nginx/snippets/signaling-forwarding.conf" failed (2: No such file or directory) in /etc/nginx/sites-enabled/nextcloud-hpb.conf:68
avril 12 14:25:57 debian nginx[16640]: nginx: configuration file /etc/nginx/nginx.conf test failed
avril 12 14:25:57 debian systemd[1]: nginx.service: Control process exited, code=exited, status=1/FAILURE
avril 12 14:25:57 debian systemd[1]: nginx.service: Failed with result 'exit-code'.
avril 12 14:25:57 debian systemd[1]: Failed to start A high performance web server and a reverse proxy server.

**Comment by uruzFR** [comment]
**JANUS Status**

● janus.service - Janus WebRTC gateway
     Loaded: loaded (/lib/systemd/system/janus.service; enabled; vendor preset: enabled)
     Active: deactivating (stop-sigterm) (Result: exit-code) since Wed 2023-04-12 14:22:04 CEST; 46min ago
       Docs: https://janus.conf.meetecho.com/docs/index.html
    Process: 18239 ExecStart=/usr/bin/janus --disable-colors --daemon --log-stdout (code=exited, status=1/FAILURE)
      Tasks: 1 (limit: 2186)
     Memory: 2.2M
        CPU: 26ms
     CGroup: /system.slice/janus.service
             └─18240 /usr/bin/janus --disable-colors --daemon --log-stdout

avril 12 15:06:59 debian janus[18240]: [Wed Apr 12 15:06:59 2023] Token based authentication disabled
avril 12 15:06:59 debian janus[18240]: [Wed Apr 12 15:06:59 2023] Initializing recorder code
avril 12 15:06:59 debian janus[18240]: [Wed Apr 12 15:06:59 2023] Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, full-trickle, IPv6 support disabled)
avril 12 15:06:59 debian janus[18240]: [Wed Apr 12 15:06:59 2023] STUN server to use: xxxxx.xx:5349
avril 12 15:06:59 debian janus[18240]: [Wed Apr 12 15:06:59 2023]   >> 127.0.1.1:5349 (IPv4)
avril 12 15:06:59 debian janus[18240]: [Wed Apr 12 15:06:59 2023] Testing STUN server: message is of 20 bytes
avril 12 15:07:04 debian janus[18240]: [Wed Apr 12 15:07:04 2023] [FATAL] [ice.c:janus_ice_test_stun_server:1078] No response to our STUN BINDING test
avril 12 15:07:04 debian janus[18240]: [Wed Apr 12 15:07:04 2023] [FATAL] [janus.c:main:4988] Invalid STUN address xxxxx.xxxxxx.xx:5349
avril 12 15:07:04 debian janus[18239]: Error launching Janus (error code 1), check the logs for more details
avril 12 15:07:04 debian systemd[1]: janus.service: Control process exited, code=exited, status=1/FAILURE

**Comment by uruzFR** [comment]
This time nginx successful launch but Janus not

```
root@debian:/home/uruz/nextcloud-high-performance-backend-setup-1.2.3# systemctl status nginx
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-04-12 15:23:58 CEST; 16s ago
       Docs: man:nginx(8)
    Process: 24467 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 24468 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
   Main PID: 24469 (nginx)
      Tasks: 3 (limit: 2186)
     Memory: 3.5M
        CPU: 46ms
     CGroup: /system.slice/nginx.service
             ├─24469 nginx: master process /usr/sbin/nginx -g daemon on; master_process on;
             ├─24470 nginx: worker process
             └─24471 nginx: worker process

avril 12 15:23:58 debian systemd[1]: Starting A high performance web server and a reverse proxy server...
avril 12 15:23:58 debian systemd[1]: Started A high performance web server and a reverse proxy server.
```


```
root@debian:/home/uruz/nextcloud-high-performance-backend-setup-1.2.3# systemctl status janus
● janus.service - Janus WebRTC gateway
     Loaded: loaded (/lib/systemd/system/janus.service; enabled; vendor preset: enabled)
     Active: activating (start) since Wed 2023-04-12 15:25:31 CEST; 4s ago
       Docs: https://janus.conf.meetecho.com/docs/index.html
Cntrl PID: 24595 (janus)
      Tasks: 3 (limit: 2186)
     Memory: 2.8M
        CPU: 23ms
     CGroup: /system.slice/janus.service
             ├─24595 /usr/bin/janus --disable-colors --daemon --log-stdout
             └─24596 /usr/bin/janus --disable-colors --daemon --log-stdout

avril 12 15:25:31 debian janus[24596]: Debug/log timestamps are enabled
avril 12 15:25:31 debian janus[24596]: Debug/log colors are disabled
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] Adding 'vmnet' to the ICE ignore list...
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] Using 192.168.1.85 as local IP...
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] Token based authentication disabled
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] Initializing recorder code
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, full-trickle, IPv6 support disabled)
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] STUN server to use: xxxxxxx:5349
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023]   >> 127.0.1.1:5349 (IPv4)
avril 12 15:25:31 debian janus[24596]: [Wed Apr 12 15:25:31 2023] Testing STUN server: message is of 20 bytes
```

```
Every installation completed.
Enabling and restarting services…
Enabling and restarting service 'ufw'…
Synchronizing state of ufw.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable ufw
Enabling and restarting service 'coturn'…
Enabling and restarting service 'nats-server'…
Enabling and restarting service 'nextcloud-spreed-signaling'…
Enabling and restarting service 'janus'…
Synchronizing state of janus.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable janus
Job for janus.service failed because the control process exited with error code.
See "systemctl status janus.service" and "journalctl -xe" for details.
Something went wrong while enabling/starting service 'janus'…
Enabling and restarting service 'nginx'…
Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
```

**Comment by uruzFR** [comment]
The service restart every 5s

```
avril 12 14:41:09 debian janus[17250]: ---------------------------------------------------
avril 12 14:41:09 debian janus[17250]:   Starting Meetecho Janus (WebRTC Server) v1.0.1
avril 12 14:41:09 debian janus[17250]: ---------------------------------------------------
avril 12 14:41:09 debian janus[17250]: Checking command line arguments...
avril 12 14:41:09 debian janus[17250]: Debug/log level is 4
avril 12 14:41:09 debian janus[17250]: Debug/log timestamps are enabled
avril 12 14:41:09 debian janus[17250]: Debug/log colors are disabled
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] Adding 'vmnet' to the ICE ignore list...
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] Using 192.168.1.85 as local IP...
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] Token based authentication disabled
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] Initializing recorder code
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] Initializing ICE stuff (Full mode, ICE-TCP candidates disabled, full-trickle, IPv6 support disabled)
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] STUN server to use: xxxxxxx:5349
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023]   >> 127.0.1.1:5349 (IPv4)
avril 12 14:41:09 debian janus[17250]: [Wed Apr 12 14:41:09 2023] Testing STUN server: message is of 20 bytes
avril 12 14:41:14 debian janus[17250]: [Wed Apr 12 14:41:14 2023] [FATAL] [ice.c:janus_ice_test_stun_server:1078] No response to our STUN BINDING test
avril 12 14:41:14 debian janus[17250]: [Wed Apr 12 14:41:14 2023] [FATAL] [janus.c:main:4988] Invalid STUN address xxxxxx:5349

```

**Comment by uruzFR** [comment]
@dzatoah I reinstalled a debian vm and did all the script but I still have the same problem with Janus but still I copy the verification email and the nginx site works.

**Comment by mircokam** [comment]
Is this maschine with an ip adresse direkt in the internet? We design this script for maschines they stand direkt in the internet an not behind a firewall or any nat proxys.

**Comment by uruzFR** [comment]
My machine is not directly connected to the internet with a public IP address. It is behind a router and I have forwarded ports 80, 443, and 5349 to it so that it can be accessed from the internet through those ports.

**Comment by mircokam** [comment]
This is the problem! These script is only for maschines that stand direktly in the internet.
Sorry ;-)

**Comment by uruzFR** [comment]
@mircokam but how can I make this server? , I need what

**Comment by mircokam** [comment]
Maybe you can get some cloud server here:
https://www.hetzner.com/de/cloud
Or you could search on the internet on how to set up a server with a publib IP with Debian.

**Comment by uruzFR** [comment]
In fact I don’t understand, I have another server (on another public ip) that executes a simple coturn server and works really well.
Now on my second server you tell me that this cannot work because there is an ip problem while I am in EXACTLY the same condition as my first coturn server.
I want to understand.

**Comment by PhilDevProg** [comment]
But didn't you say, your machine doesn't have a public IP?
> My machine is not directly connected to the internet with a public IP address.

And a simple coturn server is not comparable with the Nextcloud High Performance Backend. This script is only for servers that have a public IP and don't use a Firewall or a NAT. I hope you understand but this isn't the right place to discuss how to setup HPB for your specific situation. Please contact an expert for your situation or rent the services at a provider.

**Comment by uruzFR** [comment]
Yes, I stated that my machine is not directly connected to the internet with a public IP. I mentioned that it is behind a router, and I have opened the ports, but I am still able to access the basic nginx site from the internet.
