### ISSUE TITLE
janus lib paths incorrect for ARM based hosts

### ISSUE THREAD

**Issue by lekanteto** [sunweaver/nextcloud-high-performance-backend-setup#98]
In "janus.jcfg" the path go to 
        plugins_folder = "/usr/lib/x86_64-linux-gnu/janus/plugins"                      # Plugins folder
        transports_folder = "/usr/lib/x86_64-linux-gnu/janus/transports"        # Transports folder
        events_folder = "/usr/lib/x86_64-linux-gnu/janus/events"                        # Event handlers folder
        loggers_folder = "/usr/lib/x86_64-linux-gnu/janus/loggers"                      # External loggers folder

but on ARM based hosts the files are installed under
/usr/lib/aarch64-linux-gnu/janus

**Comment by madscientist159** [comment]
Seeing the same thing on OpenPOWER hosts, where the path should be `powerpc64le-linux-gnu`
