### ISSUE TITLE
Misleading filename deploying signalling config to nginx

### ISSUE THREAD

**Issue by jooooaah** [sunweaver/nextcloud-high-performance-backend-setup#99]
Hi there,

i tried to install the nhpb with this wonderful script, i followed the instructions exactly and set up on a fresh debian 11. It struggles at following point:

Step 5: Deploy configuration
Deploying /etc/nginx/snippets/signaling-upstream-servers.conf
cp: cannot create regular file '/etc/nginx/snippets/signaling-upstream-servers.conf': No such file or directory
Deploying /etc/nginx/snippets/signaling-forwarding.conf
cp: cannot create regular file '/etc/nginx/snippets/signaling-forwarding.conf': No such file or directory

This caused nginx not to start up. I tried to fix it manually and copied the files manually from the tmp-directory and it works. Perhaps sth goes wrong by copying the files,  don't know what.  According to the cp command in the script (setup-signaling.sh), this should not be the case. 

```
 function signaling_step5() {
        log "\nStep 5: Deploy configuration"

        deploy_file "$TMP_DIR_PATH"/signaling/nginx-signaling-upstream-servers.conf /etc/nginx/snippets/signaling-upstream-servers.conf || true
        deploy_file "$TMP_DIR_PATH"/signaling/nginx-signaling-forwarding.conf /etc/nginx/snippets/signaling-forwarding.conf || true
```

`

**Comment by dzatoah** [comment]
This probably means that the directory `/etc/nginx/snippets/` was not created yet.
This should be easily fixed with a `mkdir -p "/etc/nginx/snippets/"` before the cp.

**Comment by dzatoah** [comment]
`cp: cannot create regular file '/etc/nginx/snippets/signaling-forwarding.conf': No such file or directory` Maybe it was created too late?

**Comment by jooooaah** [comment]
Sorry for not being clear:  directory was created by script before I copied files manually

21.04.2023 09:59:36 Daniel ***@***.***>:

**Comment by madscientist159** [comment]
Just hit this same bug on a new Debian Bullseye instance.  Nothing created in nginx snippets directory, HP server inaccessible as a result.

**Comment by HB9HIL** [comment]
+1
Had to create the two files manually after the script was finished

**Comment by jooooaah** [comment]
Just tested, thank's a lot - worked perfectly
